### ISSUE TITLE
Add integration not possible: [%key:common::config_flow::error::unknown%]

### ISSUE THREAD

**Issue by Matzll** [chris60600/pollens-home-assistant#19]
After installing the integration and restart homeassistant its not possible to add the integration for two departments: Haute-Corse and Corse-du-Sud.

The following error is shown:
[%key:common::config_flow::error::unknown%]
![20231025_pollens_issue](https://github.com/chris60600/pollens-home-assistant/assets/10441788/35706a60-8edd-4c28-9cb2-07445670943e)

Here are the logs:
Unexpected exception

Traceback (most recent call last):
  File "/config/custom_components/pollens/config_flow.py", line 74, in async_step_user
    self._init_info["info"] = await validate_input(self.hass, user_input)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pollens/config_flow.py", line 44, in validate_input
    result = await client.Get(data[CONF_COUNTRYCODE])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pollens/pollensasync.py", line 43, in Get
    request_json = json.loads(request_json)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Other departments works fine.

**Comment by chris60600** [comment]
Maybe a problème with 2A ans 2B ! I never tested them

**Comment by chris60600** [comment]
Bug fix in v2023.11.1
