### ISSUE TITLE
Version 2021.12.14 released today is broken.

### ISSUE THREAD

**Issue by FredericGuardia** [chris60600/pollens-home-assistant#4]
We get an error message inside HA Core log during component initialiatization after upgrade through HACS. 

This is the error message found inside HA Core log:

```
2021-12-14 21:27:44 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up pollens platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/pollens/sensor.py", line 114, in async_setup_platform
    pollens_sensor = PollensSensor(client, county_number, county_name)
TypeError: __init__() missing 1 required positional argument: 'pollens_filter'
```

'pollens_filter' argument is missing at line 114 of sensor.py file. For fixing  issue, this line should be changed to this:
`pollens_sensor = PollensSensor(client, county_number, county_name, pollens_filter)`

**Comment by chris60600** [comment]
Fixed
