### ISSUE TITLE
Traceback on start

### ISSUE THREAD

**Issue by chris60600** [chris60600/pollens-home-assistant#6]
Traceback error when start ha

> 2022-02-01 18:18:07 ERROR (MainThread) [homeassistant.config] Platform error: sensor
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config.py", line 887, in async_process_component_config
>     platform = p_integration.get_platform(domain)
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
>     cache[full_name] = self._import_platform(platform_name)
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
>     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
>   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/config/custom_components/pollens/sensor.py", line 26, in <module>
>     from config.custom_components import pollens
> ModuleNotFoundError: No module named 'config.custom_components'

- [x] Remove line 26 in sensor.p

**Comment by chris60600** [comment]
Fixed
